apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: ens6f0np0
  namespace: openshift-sriov-network-operator
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  resourceName: ens6f0np0
  needVhostNet: false
  isRdma: false
  numVfs: 8
  nicSelector:
    pfNames: ["ens6f0np0#1-7"]
