apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cssr-test
  name: modules 
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
